version: '3'
networks:
  net-1:
services:
  wg-1:
    image: localhost/smegmesh-base:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    networks:
      - net-1
    volumes:
      - ./shared:/shared
    command: "smegd /shared/configuration.yaml"
    sysctls:
      - net.ipv6.conf.all.forwarding=1
  wg-2:
    image: localhost/smegmesh-base:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    networks:
      - net-1
    volumes:
      - ./shared:/shared
    command: "smegd /shared/configuration.yaml"
    sysctls:
      - net.ipv6.conf.all.forwarding=1
  wg-3:
    image: localhost/smegmesh-base:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    networks:
      - net-1
    volumes:
      - ./shared:/shared
    command: "smegd /shared/configuration.yaml"
    sysctls:
      - net.ipv6.conf.all.forwarding=1
