version: '3'
networks:
  net-1:
    enable_ipv6: true
    ipam:
       driver: default
       config:
         - subnet: 2001:db8::/64
services:
  wg-1:
    image: smegmesh-base:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    networks:
      - net-1
    volumes:
      - ./shared:/shared
    command: "smegd /shared/configuration.yaml"
    sysctls:
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
  wg-2:
    image: smegmesh-base:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    networks:
      - net-1
    volumes:
      - ./shared:/shared
    command: "smegd /shared/configuration.yaml"
    sysctls:
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
  wg-3:
    image: smegmesh-base:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    networks:
      - net-1
    volumes:
      - ./shared:/shared
    command: "smegd /shared/configuration.yaml"
    sysctls:
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
